-- REMOVED 2026-07-03. Replaced by secondbrain/catalog/schema.sql — see
-- docs/decisions.md for why the versioned-migration-file concept was
-- dropped before this database holds any real data.
--
-- (This file could not be deleted from disk due to a sandbox permissions
-- issue; it is intentionally left empty and unused. Safe to delete by hand,
-- along with the now-empty migrations/ directory.)
